//
//  AIAnalysis.swift
//  WakeFit
//
//  SwiftData model for storing AI-generated nutrition analysis
//  Generated by OpenAI API when user taps "Analyze My Day"
//

import Foundation
import SwiftData

@Model  // Makes this class storable in SwiftData
final class AIAnalysis {
    var id: UUID
    var date: Date               // Which day was analyzed
    var estimatedCalories: Int   // Total calories AI estimated
    var estimatedProtein: Int    // Total protein in grams
    var riskAreas: String        // What went wrong (e.g., "High sugar snacks")
    var disciplineStatus: String // "Disciplined" | "Borderline" | "Off Track"
    var coachDiagnosis: String   // AI's 2-3 sentence assessment
    var tomorrowAdvice: String   // AI's 1-2 sentence advice for next day

    init(
        id: UUID = UUID(),
        date: Date,
        estimatedCalories: Int,
        estimatedProtein: Int,
        riskAreas: String,
        disciplineStatus: String,
        coachDiagnosis: String,
        tomorrowAdvice: String
    ) {
        self.id = id
        self.date = date
        self.estimatedCalories = estimatedCalories
        self.estimatedProtein = estimatedProtein
        self.riskAreas = riskAreas
        self.disciplineStatus = disciplineStatus
        self.coachDiagnosis = coachDiagnosis
        self.tomorrowAdvice = tomorrowAdvice
    }
}
